# Generated by Django 4.2.7 on 2023-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0003_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('translation_key', 'locale'), ('locale', 'slug')},
        ),
    ]
